"""Make company_id and project_id nullable for anonymous conversations

Revision ID: 22186259fe47
Revises: 10b4566d7e9a
Create Date: 2025-10-15 19:25:00.356115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22186259fe47'
down_revision: Union[str, Sequence[str], None] = '10b4566d7e9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip creating unique constraint as it already exists
    op.alter_column('conversations', 'company_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('conversations', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('conversations', 'company_id',
               existing_type=sa.UUID(),
               nullable=False)
    # Skip dropping unique constraint as it should remain
    # ### end Alembic commands ###
